name: sample-laravel
services:
- environment_slug: php
  name: web
  build_command: composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build
  run_command: php artisan serve --host=0.0.0.0 --port=8080
  envs:
  - key: APP_NAME
    value: "Laravel"
  - key: APP_ENV
    value: "local"
  - key: APP_KEY
    value: ${APP_KEY}
  - key: APP_DEBUG
    value: "true"
  - key: APP_URL
    value: "http://localhost"
  - key: LOG_CHANNEL
    value: "stack"
  - key: DB_CONNECTION
    value: "mysql"
  - key: DB_HOST
    value: "127.0.0.1"
  - key: DB_PORT
    value: "3306"
  - key: DB_DATABASE
    value: "laravel"
  - key: DB_USERNAME
    value: "root"
  - key: DB_PASSWORD
    value: ""
  - key: BROADCAST_DRIVER
    value: "log"
  - key: CACHE_DRIVER
    value: "file"
  - key: QUEUE_CONNECTION
    value: "sync"
  - key: SESSION_DRIVER
    value: "file"
  - key: SESSION_LIFETIME
    value: "120"
  - key: REDIS_HOST
    value: "127.0.0.1"
  - key: REDIS_PASSWORD
    value: "null"
  - key: REDIS_PORT
    value: "6379"
  - key: MAIL_MAILER
    value: "smtp"
  - key: MAIL_HOST
    value: "smtp.mailtrap.io"
  - key: MAIL_PORT
    value: "2525"
  - key: MAIL_USERNAME
    value: "null"
  - key: MAIL_PASSWORD
    value: "null"
  - key: MAIL_ENCRYPTION
    value: "null"
  - key: MAIL_FROM_ADDRESS
    value: "null"
  - key: MAIL_FROM_NAME
    value: ${APP_NAME}
  - key: AWS_ACCESS_KEY_ID
    value: ""
  - key: AWS_SECRET_ACCESS_KEY
    value: ""
  - key: AWS_DEFAULT_REGION
    value: "us-east-1"
  - key: AWS_BUCKET
    value: ""
  - key: PUSHER_APP_ID
    value: ""
  - key: PUSHER_APP_KEY
    value: ""
  - key: PUSHER_APP_SECRET
    value: ""
  - key: PUSHER_APP_CLUSTER
    value: "mt1"
  - key: MIX_PUSHER_APP_KEY
    value: ${PUSHER_APP_KEY}
  - key: MIX_PUSHER_APP_CLUSTER
    value: ${PUSHER_APP_CLUSTER}
  - key: QUEUE_CONNECTION
    value: "sync"
  - key: SESSION_DRIVER
    value: "file"
  - key: SESSION_LIFETIME
    value: "120"
  - key: MEMCACHED_HOST
    value: "127.0.0.1"
  - key: REDIS_HOST
    value: "127.0.0.1"
  - key: REDIS_PORT
    value: "6379"
  - key: MAIL_MAILER
    value: "log"
  - key: MAIL_HOST
    value: "127.0.0.1"
  - key: MAIL_PORT
    value: "2525"
  - key: MAIL_USERNAME
    value: "null"
  - key: MAIL_PASSWORD
    value: "null"
  - key: PUSHER_APP_ID
    value: ${PUSHER_APP_ID}
  - key: PUSHER_APP_KEY
    value: ${PUSHER_APP_KEY}
  - key: PUSHER_APP_SECRET
    value: ${PUSHER_APP_SECRET}
  - key: PUSHER_HOST
    value: ${PUSHER_HOST}
  - key: PUSHER_PORT
    value: ${PUSHER_PORT}
  - key: PUSHER_SCHEME
    value: ${PUSHER_SCHEME}
  - key: PUSHER_APP_CLUSTER
    value: ${PUSHER_APP_CLUSTER}
  - key: VITE_PUSHER_APP_KEY
    value: ${PUSHER_APP_KEY}
  - key: VITE_PUSHER_HOST
    value: ${PUSHER_HOST}
  - key: VITE_PUSHER_PORT
    value: ${PUSHER_PORT}
  - key: VITE_PUSHER_SCHEME
    value: ${PUSHER_SCHEME}
  - key: VITE_PUSHER_APP_CLUSTER
    value: ${PUSHER_APP_CLUSTER}
  - key: MIX_PUSHER_APP_KEY
    value: ${PUSHER_APP_KEY}
  - key: MIX_PUSHER_APP_CLUSTER
    value: ${PUSHER_APP_CLUSTER}
    value: "null"
  - key: MAIL_ENCRYPTION
    value: "null"
  - key: MAIL_FROM_ADDRESS
    value: "hello@example.com"
  - key: MAIL_FROM_NAME
    value: "${APP_NAME}"
  http_port: 8080
  source_dir: /
